# Site settings
title: Richard Gibert
email: richard@gibert.ca
author: Richard Gibert
description: >-
    Richard Gibert's web site and knowledge base
baseurl: ""
url: "https://richard.gibert.ca"

repository: rgibert/rgibert.github.io

# Build settings
remote_theme: just-the-docs/just-the-docs@v0.12.0
markdown: kramdown
permalink: /:year/:title/

# Collections
collections:
    docs:
        output: true
        permalink: /:collection/:path

# Defaults
defaults:
    - scope:
        path: ""
        type: "pages"
      values:
        layout: default
    - scope:
        path: ""
        type: "docs"
      values:
        layout: default
    - scope:
        path: ""
        type: "posts"
      values:
        layout: default

# Just the Docs options
search_enabled: true
heading_anchors: true
nav_enabled: true
color_scheme: dark
favicon_ico: /assets/favicons/favicon.ico
back_to_top: true
enable_copy_code_button: true

# Copy dot-directories (e.g. /.well-known/) as static files
include:
    - .well-known

# Aux links for the upper right navigation
aux_links:
    "GitHub":
        - "https://github.com/rgibert"
    "LinkedIn":
        - "https://www.linkedin.com/in/richard-gibert/"
    "Strava":
        - "https://www.strava.com/athletes/rgibert/"
aux_links_new_tab: true

# Footer "Edit this page on GitHub" link
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/rgibert/rgibert.github.io"
gh_edit_branch: master

plugins:
    - jekyll-redirect-from

exclude: [CHANGELOG.md, LICENSE, README.md, vendor]